### ISSUE TITLE
Flag needs to be imported from .env file

### ISSUE THREAD

**Issue by wg4568** [wg4568/my-cool-app#1]
We need to read the flag from an environment flag to be displayed to the user. Don't forget to add it to gitignore so that it's not shared publicly.

**Comment by vlexvnder** [comment]
I gotchu king

**Comment by vlexvnder** [comment]
quick fix, #2

**Comment by wg4568** [comment]
ur pull request was rejected. I'll do it myself :man_facepalming:

**Comment by wg4568** [comment]
Fixed!
